# Generated by Django 4.1.7 on 2023-05-25 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_brand_name_alter_seller_name_alter_type_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.brand')),
                ('_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
                ('_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.seller')),
                ('_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.type')),
            ],
        ),
    ]
