# Generated by Django 4.1.7 on 2023-05-25 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='_brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='_seller',
            new_name='seller',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='_type',
            new_name='type',
        ),
    ]
