# Generated by Django 4.1.7 on 2023-05-25 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename__brand_product_brand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='product_type',
        ),
    ]
