# Generated by Django 4.1.7 on 2023-05-25 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_type_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.warranty'),
        ),
    ]
